### ISSUE TITLE
Cannot access couchdb at port :5984 ? 

### ISSUE THREAD

**Issue by Ammarkhalid047** [togettoyou/fabric-realty#23]
I am not able to access **ledger / couchdb** at port **5984**. Can you please guide me where can i access the ledger or database?

**Comment by togettoyou** [comment]
Hi @Ammarkhalid047 . The default is goleveldb. If you want to switch CouchDB ,

You can change this file : https://github.com/togettoyou/fabric-realty/blob/main/network/docker-compose-base.yaml#L12

```yaml
- CORE_LEDGER_STATE_STATEDATABASE=CouchDB
- CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
# The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
# provide the credentials for ledger to connect to CouchDB.  The username and password must
# match the username and password set for the associated CouchDB.
- CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
- CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
```

You also need to add the CouchDB service :

```yaml
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
```
